const pages=['首页','学习计划','单词','语法','读解','听解','专项练习','模考','错题本','收藏','统计','官方资料'];
const nav=document.querySelector('#nav'), app=document.querySelector('#app');
let state=JSON.parse(localStorage.getItem('n1os')||'{"done":{},"words":0,"grammar":0,"wrong":[],"days":[],"wordSrs":{}}');
if(!state.wordSrs) state.wordSrs={};
const save=()=>localStorage.setItem('n1os',JSON.stringify(state));
function countdown(){const target=new Date('2027-12-05T09:00:00');const d=Math.max(0,Math.ceil((target-new Date())/86400000));document.querySelector('#countdown').textContent=`あと ${d} 日（暂定）`};countdown();
function render(p,b){[...nav.children].forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');document.querySelector('#pageTitle').textContent=p==='首页'?'今日の学習':p; app.innerHTML=views[p]();bind(p)}
const taskData=[['単語','新词 20 + 复习 30','20 min'],['文法','N1 核心语法 3 条','15 min'],['読解','中篇阅读 1 篇','15 min'],['聴解','ポイント理解练习','20 min'],['復習','昨日错题','10 min']];
const views={
'首页':()=>{let n=Object.values(state.done).filter(Boolean).length;return `<div class=grid><div class='card span8'><h2>今日の学習 <span class=tag>${n}/5</span></h2>${taskData.map((t,i)=>`<label class=task><input type=checkbox data-task=${i} ${state.done[i]?'checked':''}><span class=grow><b>${t[0]}</b><br><span class=muted>${t[1]}</span></span><span class=pill>${t[2]}</span></label>`).join('')}</div><div class='card span4'><h2>今日の進捗</h2><div class=big>${n*20}%</div><div class=bar><i style='width:${n*20}%'></i></div><p class=muted>每日完成一点，比临考突击更重要。</p></div><div class='card span8'><h2>Road to N1</h2><p><b>Phase 1 · 基础构建</b>　2026.10 — 2027.02</p><div class=bar><i style='width:3%'></i></div><p class=muted>当前重点：建立 N1 词汇/语法基础，并养成持续听力输入。</p></div><div class='card span4'><h2>弱点</h2><p class=notice>数据积累中。完成练习后，这里会自动显示正确率最低的题型。</p></div></div>`},
'学习计划':()=>`<div class=grid>${[['2026.10 — 2027.02','基础构建','词汇、语法第一轮；每天 20 分钟听力'],['2027.03 — 06','系统学习','完成 N1 核心知识；系统加入阅读'],['2027.07 — 09','专项强化','阅读速度、听力题型、弱项训练'],['2027.10 — 11','模考期','完整套题、计时、错题回炉'],['2027.12','冲刺','保持手感、复习高频错题']].map(x=>`<div class='card span6'><span class=tag>${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p></div>`).join('')}</div>`,
'单词':()=>wordFlashcards(),
'语法':()=>study('文法','〜にひきかえ','接续：名詞＋にひきかえ','与……相反；相比之下','去年は暖冬だった（　）、今年は非常に寒い。',['にひきかえ','を皮切りに','に至って','をものともせず'],0),
'读解':()=>`<div class=card><span class=tag>読解 · 中篇</span><h2>计时阅读训练</h2><p class=muted>建议 7:00 内完成</p><div class=question>便利さを追求することは、必ずしも生活を豊かにするとは限らない。時間を節約する道具が増えたにもかかわらず、私たちは以前より忙しいと感じている……</div><p><b>作者最想表达什么？</b></p><div class=choices><button>便利的工具应该减少使用</button><button data-correct=1>便利与生活的充实并不必然一致</button><button>现代人没有时间观念</button><button>技术发展让人更加幸福</button></div><p id=feedback></p></div>`,
'听解':()=>`<div class=grid><div class='card span8'><span class=tag>聴解 · ポイント理解</span><h2>音频训练区</h2><p>正式版这里用于播放你导入的合法音频材料；第一次作答时不显示 transcript。</p><div class=question>▶︎　00:00 ━━━━━━━━━ 00:42<br><small>0.8×　1.0×　1.2×</small></div><button class=btn id=transcript>提交后查看 Transcript</button><p id=trans hidden>Transcript / 答案依据会显示在这里。</p></div><div class='card span4'><h2>训练原则</h2><p>① 不看字幕作答<br>② 核对答案<br>③ 精听错误位置<br>④ 最后查看文本</p></div></div>`,
'专项练习':()=>`<div class=grid>${['近义词辨析','助词・接续','文章主旨','信息检索','即時応答','統合理解'].map(x=>`<div class='card span4'><h2>${x}</h2><p class=muted>完成更多练习后自动生成针对性题组。</p><button class='btn secondary'>开始练习</button></div>`).join('')}</div>`,
'模考':()=>`<div class=grid><div class='card span6'><span class=tag>SECTION 1</span><h2>言語知識・読解</h2><div class=big>110:00</div><p>完整计时模拟。建议进入模考阶段后使用。</p></div><div class='card span6'><span class=tag>SECTION 2</span><h2>聴解</h2><div class=big>約 55:00</div><p>连续播放，模拟正式考试节奏。</p></div><div class='card span12'><button class=btn>开始一次模拟考试</button> <span class=muted>当前为框架版；题库会逐步扩充。</span></div></div>`,
'错题本':()=>`<div class=card><h2>自動収集された間違い</h2>${state.wrong.length?state.wrong.map(x=>`<div class=task><span class=pill>${x.type}</span><span>${x.q}</span></div>`).join(''):'<p class=muted>还没有错题。做错的练习会自动出现在这里。</p>'}</div>`,
'收藏':()=>`<div class=card><h2>收藏夹</h2><p class=muted>以后可收藏单词、语法、阅读文章与错题。</p></div>`,
'统计':()=>`<div class=grid><div class='card span12'><div class=metrics>${[['学习天数',state.days.length],['掌握词汇',state.words],['语法',state.grammar],['错题',state.wrong.length]].map(x=>`<div class=metric><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div><div class='card span6'><h2>近 7 日学习量</h2><div class=week>${[25,55,35,80,60,90,45].map(h=>`<i style='height:${h}%'></i>`).join('')}</div></div><div class='card span6'><h2>能力趋势</h2><p>語彙　—　数据积累中</p><p>文法　—　数据积累中</p><p>読解　—　数据积累中</p><p>聴解　—　数据积累中</p></div></div>`,
'官方资料':()=>`<div class=grid><div class='card span6 resource'><h2>JLPT 官方样题</h2><p>使用官方 Sample Questions 熟悉 N1 题型。</p><a href='https://www.jlpt.jp/e/samples/forlearners.html' target=_blank>打开 JLPT 官方页面 ↗</a></div><div class='card span6 resource'><h2>Official Practice Workbook</h2><p>官方练习册、答案与听力材料入口。</p><a href='https://www.jlpt.jp/e/samples/sampleindex.html' target=_blank>打开官方 Practice Workbook ↗</a></div><div class='card span12'><p class=notice>版权材料不直接复制进本站。你合法拥有的教材/PDF/音频后续可以做成个人练习库。</p></div></div>`};
const wordDeck=[
{w:'見合わせる',r:'みあわせる',m:'暂缓；推迟；暂且不做',pos:'他動詞・一段',ex:'悪天候のため、試合の開催を見合わせることになった。',er:'あくてんこう の ため、しあい の かいさい を みあわせる こと に なった。',cn:'因天气恶劣，决定暂缓举行比赛。',coll:'開催を見合わせる / 発表を見合わせる',note:'不一定等于取消，更接近“暂缓、观望后再决定”。'},
{w:'促す',r:'うながす',m:'催促；促使；推动',pos:'他動詞・五段',ex:'政府は企業に対して、働き方の見直しを促した。',er:'せいふ は きぎょう に たいして、はたらきかた の みなおし を うながした。',cn:'政府敦促企业重新审视工作方式。',coll:'注意を促す / 改善を促す / 行動を促す',note:'常用于较正式语境，表示推动对方采取行动或发生变化。'},
{w:'滞る',r:'とどこおる',m:'停滞；拖延；不顺畅',pos:'自動詞・五段',ex:'大雪の影響で、商品の配送が滞っている。',er:'おおゆき の えいきょう で、しょうひん の はいそう が とどこおっている。',cn:'受大雪影响，商品配送出现了延误。',coll:'支払いが滞る / 交通が滞る / 業務が滞る',note:'强调原本应该顺利进行的事情卡住、延迟。'},
{w:'免れる',r:'まぬかれる',m:'避免；幸免；摆脱',pos:'他動詞・一段',ex:'早めに避難したため、大きな被害を免れた。',er:'はやめ に ひなん した ため、おおきな ひがい を まぬかれた。',cn:'因为提前避难，避免了重大损失。',coll:'責任を免れる / 被害を免れる / 処罰を免れる',note:'常与负面结果搭配，表示没有遭受本来可能发生的不利情况。'},
{w:'著しい',r:'いちじるしい',m:'显著的；明显的；惊人的',pos:'い形容詞',ex:'この地域では人口の減少が著しい。',er:'この ちいき では じんこう の げんしょう が いちじるしい。',cn:'这个地区的人口减少十分显著。',coll:'著しい成長 / 著しい変化 / 著しく増加する',note:'比「大きい」更正式，常用于变化、增长、下降等程度非常明显的情况。'}];
let wordIndex=0, wordRevealed=false;
function wordFlashcards(){const x=wordDeck[wordIndex%wordDeck.length];const rec=state.wordSrs[x.w]||{};return `<div class=grid><div class='card span8 flashcard'><div class=flash-top><span class=tag>語彙 · Flashcard</span><span class=progress-mini>${wordIndex%wordDeck.length+1} / ${wordDeck.length} · ${rec.level||'New'}</span></div><h2 class=flash-word>${x.w}</h2><div class=flash-reading>${x.r}</div>${wordRevealed?`<div class=answer-panel><p class=meaning>${x.m}</p><div class=example><b>${x.ex}</b><div class=example-reading>${x.er}</div><div>${x.cn}</div></div><div class=meta-row><b>词性</b><span>${x.pos}</span></div><div class=meta-row><b>搭配</b><span>${x.coll}</span></div><div class=meta-row><b>提示</b><span>${x.note}</span></div><div class=srs-actions><button data-rate=again>不会<br><small>很快再看</small></button><button data-rate=hard>模糊<br><small>加强复习</small></button><button data-rate=good>认识<br><small>延后复习</small></button></div>`:`<div class=reveal><p class=muted>先在脑中回忆词义，再显示答案。</p><button class=btn id=revealWord>显示答案</button></div>`}</div><div class='card span4'><h2>学习方式</h2><p>① 看单词与读音并回忆</p><p>② 显示释义、例句与完整读法</p><p>③ 选择掌握程度</p><p>④ 系统记录状态并安排复习</p><div class=notice>选择题已从“学习”移出，之后放到“练习 → 語彙”。</div></div></div>`}
function rateWord(rate){const x=wordDeck[wordIndex%wordDeck.length], now=Date.now();const cfg={again:['Learning',10*60e3],hard:['Learning',24*60*60e3],good:['Familiar',3*24*60*60e3]}[rate];state.wordSrs[x.w]={level:cfg[0],last:now,due:now+cfg[1],reviews:(state.wordSrs[x.w]?.reviews||0)+1};if(rate==='good')state.words=Object.values(state.wordSrs).filter(v=>v.level==='Familiar'||v.level==='Mastered').length;if(!state.days.includes(new Date().toDateString()))state.days.push(new Date().toDateString());save();wordIndex=(wordIndex+1)%wordDeck.length;wordRevealed=false;render('单词',nav.children[pages.indexOf('单词')])}
function study(type,title,reading,meaning,q,choices,correct){return `<div class=grid><div class='card span8'><span class=tag>${type}</span><h2>${title}</h2><p>${reading}</p><p class=big style='font-size:24px'>${meaning}</p><div class=question>${q}</div><div class=choices>${choices.map((c,i)=>`<button data-answer=${i} data-correct=${i===correct?1:0}>${String.fromCharCode(65+i)}　${c}</button>`).join('')}</div><p id=feedback></p></div><div class='card span4'><h2>掌握状态</h2><button class='btn secondary mastery'>认识</button> <button class='btn secondary mastery'>模糊</button> <button class='btn secondary mastery'>不会</button><p class=muted>后续版本将按掌握程度安排间隔复习。</p></div></div>`}
function bind(p){let rw=document.querySelector('#revealWord');if(rw)rw.onclick=()=>{wordRevealed=true;render('单词',nav.children[pages.indexOf('单词')])};document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rateWord(b.dataset.rate));document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>{state.done[x.dataset.task]=x.checked;if(x.checked&&!state.days.includes(new Date().toDateString()))state.days.push(new Date().toDateString());save();render('首页',nav.children[0])});document.querySelectorAll('[data-correct]').forEach(x=>x.onclick=()=>{let ok=x.dataset.correct==='1';document.querySelector('#feedback').innerHTML=ok?'<b>✓ 正解</b>':'<b>✕ 不正解</b>　已加入错题本';if(!ok){state.wrong.push({type:p,q:x.closest('.card').querySelector('.question')?.textContent||'练习题'});save()}});document.querySelectorAll('.mastery').forEach(x=>x.onclick=()=>{if(p==='单词')state.words++;if(p==='语法')state.grammar++;save();x.textContent='✓ '+x.textContent});let t=document.querySelector('#transcript');if(t)t.onclick=()=>document.querySelector('#trans').hidden=false;document.querySelector('#streak').textContent=state.days.length}

// Mobile-first bottom navigation
const mobileItems=[['首页','⌂','首页'],['学习','学','单词'],['练习','練','专项练习'],['进度','進','统计'],['我的','☰','学习计划']];
const mobileNav=document.querySelector('#mobileNav');
if(mobileNav){mobileItems.forEach(([label,icon,page])=>{const bt=document.createElement('button');bt.innerHTML=`<b>${icon}</b>${label}`;bt.onclick=()=>{const idx=pages.indexOf(page);render(page,nav.children[idx]);[...mobileNav.children].forEach(x=>x.classList.remove('active'));bt.classList.add('active')};mobileNav.appendChild(bt)});mobileNav.children[0]?.classList.add('active')}

// Initialize only after all view functions exist. This avoids Safari/GitHub Pages loading a blank shell.
pages.forEach((p)=>{const b=document.createElement('button');b.textContent=p;b.onclick=()=>render(p,b);nav.appendChild(b)});
render('首页',nav.children[0]);
